config/routes.rb
Happimetrics::Application.routes.draw do
  get "metric_values/update"

  # root dashboard path
  root :to => 'dashboard', :action => 'index'

  # metrics administration
  resources :metrics
  # metric values
  resources :metric_values

  # breakdowns
  [:day, :week, :month, :year].each do |type|
    params = case type
    when :day, :week
      "/:day/:month/:year"
    when :month
      "/:month/:year"
    when :year
      "/:year"
    end
    match "/#{type.to_s}#{params}" => "dashboard#show", :type => type, :as => type.to_s
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end

  def type
    @type ||= params[:type]
  end
  helper_method :type

  # current day, if the type is day
  def current_day
    @current_day ||= begin
      if params && params['day'] && params['month'] && params['year']
        Date.parse("#{params['day']}/#{params['month']}/#{params['year']}")
      end
    end
  end
  helper_method :current_day

  # same as current day, but represents the beginning of a given week
  def current_beginning_of_week_day
    @current_beginning_of_week_day ||= current_day
  end
  helper_method :current_beginning_of_week_day

  # grab the first day of the month from the params
  def current_beginning_of_month_day
    @current_beginning_of_month_day ||= begin
      if params && params['month'] && params['year']
        Date.parse("01/#{params['month']}/#{params['year']}")
      end
    end
  end
  helper_method :current_beginning_of_month_day

  # grab the first day of the year from the params
  def current_beginning_of_year_day
    @current_beginning_of_year_day ||= begin
      if params && params['year']
        Date.parse("01/01/#{params['year']}")
      end
    end
  end
  helper_method :current_beginning_of_year_day

  def current_uid
    @current_uid ||= begin
      case type
      when :day
        uid_for_day current_day
      when :week
        uid_for_week current_beginning_of_week_day
      when :month
        uid_for_month current_beginning_of_month_day
      when :year
        uid_for_year current_beginning_of_year_day
      end
    end
  end
  helper_method :current_uid

  def entries
    @entries ||= begin
      scope = HappinessEntry
      case type
      when :day
        scope.on_date(current_day).order("entry_time asc")
      when :week
        scope.in_week(current_beginning_of_week_day, current_beginning_of_week_day.end_of_week)
      when :month
        scope.in_month(current_beginning_of_month_day, current_beginning_of_month_day.end_of_month)
      when :year
        scope.in_month(current_beginning_of_year_day, current_beginning_of_year_day.end_of_year)
      end
    end
  end
  helper_method :entries

end

app/helpers/dashboard_helper.rb
module DashboardHelper

  # adjectivise type
  def type_adjective type
    case type
    when :day
      "daily"
    when :week
      "weekly"
    when :month
      "monthly"
    when :year
      "annual"
    end
  end

  #path for a given day
  def other_day_path day, direction
    other_day = case direction
    when :previous
      day - 1.day
    when :next
      day + 1.day
    end
    day_path(other_day.day, other_day.month, other_day.year)
  end

  # path for a given week
  def other_week_path beginning_of_week_day, direction
    other_week = case direction
    when :previous
      beginning_of_week_day - 1.week
    when :next
      beginning_of_week_day + 1.week
    end
    week_path(other_week.day, other_week.month, other_week.year)
  end

  # path for a given month
  def other_month_path beginning_of_month_day, direction
    other_month = case direction
    when :previous
      beginning_of_month_day - 1.month
    when :next
      beginning_of_month_day + 1.month
    end
    month_path(other_month.month, other_month.year)
  end

  # path for a given year
  def other_year_path beginning_of_year_day, direction
    other_year = case direction
    when :previous
      beginning_of_year_day - 1.year
    when :next
      beginning_of_year_day + 1.year
    end
    year_path(other_year.year)
  end

  def available_metric_types
    @available_metric_types ||= Metric.all_for_type(type).map(&:metric_types).flatten.uniq.sort_by(&:position)
  end

  def metric_values
    @metric_values ||= Metric.all_for_type(type).inject([]) do |arr, metric|
      metric_type = "#{type}_value"
      arr << metric.metric_values.find_or_create_by_uid_and_metric_type(current_uid, metric_type)
      arr
    end
  end

  # describe a week with options links
  def week_description date, links = false
    if links
      start_of_week = date.strftime("%d")
      start_of_week += " #{link_to(date.strftime("%B"), month_path(date.month), :class => "")}"
      start_of_week += " #{link_to(date.year, year_path(date.year), :class => "")}"
      end_of_week = date.end_of_week.strftime("%d")
      end_of_week += " #{link_to(date.end_of_week.strftime("%B"), month_path(date.end_of_week.month), :class => "")}"
      end_of_week += " #{link_to(date.end_of_week.year, year_path(date.end_of_week.year), :class => "")}"
    else
      start_of_week = date.strftime("#{date.day.ordinalize}")
      end_of_week = date.end_of_week.strftime("#{date.end_of_week.day.ordinalize}")
    end
    "#{start_of_week} to #{end_of_week}".html_safe
  end

  # Graphing bits

  # get the distributions values in a hash, dependant on type
  def all_happiness_distributions_for_chart type
    @all_happiness_distributions_for_chart ||= categories(type).inject({}) do |hash, date|
      uid = type == :year ? uid_for_month(date) : uid_for_day(date)
      distribution_type = type == :year ? :month : :day
      happiness_distributions = MetricCalculation.happiness_distribution(uid, distribution_type)
      HappinessValue.names.each do |happiness_value|
        current_value = happiness_distributions[happiness_value] ? happiness_distributions[happiness_value].round(2) : 0.0
        item = {:y => current_value}
        item[:url] = type == :year ? month_path(date.month, date.year) : day_path(date.day, date.month, date.year)
        hash[happiness_value] ? hash[happiness_value] << item : hash[happiness_value] = [item]
      end
      hash
    end
  end

  # items for the y axis
  def categories type
    @categories ||= case type
      when :week
        (current_beginning_of_week_day..current_beginning_of_week_day.end_of_week).to_a.select do |date| 
          !date.saturday? && !date.sunday?
        end
      when :month
        (current_beginning_of_month_day..current_beginning_of_month_day.end_of_month).to_a.select do |date| 
          !date.saturday? && !date.sunday?
        end
      when :year
        (current_beginning_of_year_day..current_beginning_of_year_day.end_of_year).to_a.select do |date| 
          date.day == 1
        end
    end
  end

  # names of the items for the y-axis
  def category_names(type)
    @category_names ||= case type
    when :week, :month
      categories(type).map {|date| date.strftime("%a #{date.day.ordinalize}") }
    when :year
      categories(type).map {|date| date.strftime("%B %Y") }
    end
  end

  # highchart
  def entries_graph type
    @graph = LazyHighCharts::HighChart.new('graph') do |f|
      f.options[:chart] = {:defaultSeriesType => "area", :backgroundColor => "#f7f6f4"}
      f.options[:title] = {:text => "Happiness distribution for #{type}", :style => {:fontSize => "30px", :fontFamily => "'Unica One', cursive"}}
      f.options[:subtitle] = {:text => "Click on a data point to drill down to further metric data", :y => 50, :style => {:fontSize => "14px", :fontWeight => "bold" }}
      f.options[:plotOptions][:area] = {
          stacking: 'percent',
          lineColor: '#ffffff',
          lineWidth: 1,
          marker: { lineWidth: 1, lineColor: '#ffffff'},
      }
      f.options[:plotOptions][:series] = {:cursor => "pointer", :point => { events: { click: "function() { window.open(this.options.url) }"} } }
      f.options[:colors] = ['#89A54E', '#4572A7', '#AA4643']
      f.options[:legend] = {:borderWidth => 0, :enabled => false}
      f.xAxis!(:categories => category_names(type), :tickmarkPlacement => "on", 
        :title => {:enabled => false}, :labels => {:rotation => 90, :y => 40} )
      f.yAxis(:title => { text: 'Percent' })
      HappinessValue.names.each do |happiness_value|
        f.series(:name => happiness_value.titleize, :data => all_happiness_distributions_for_chart(type)[happiness_value])
      end
    end
  end

end

app/views/dashboard/_day.html.erb
<div class="row-fluid">

  <div class='span12'>

    <div class='row-fluid title-block'>
      <div class='align-right span4'>
        <%= link_to "Previous day", other_day_path(current_day, :previous), :class => "btn btn-themed" if current_day %>
      </div>
      <div class='center span4'>
         <h1>
          <%= current_day.strftime("%A, %d") %>
          <%= link_to current_beginning_of_month_day.strftime("%B"), month_path(current_beginning_of_month_day.month), :class => "" %>
          <%= link_to current_beginning_of_month_day.year, year_path(current_beginning_of_month_day.year), :class => "" %>
        </h1>
      </div>
      <div class='align-left span4'>
        <%= link_to "Following day", other_day_path(current_day, :next), :class => "btn" if current_day %>
      </div>      
    </div>

    <% if entries.any? %>
      <%= render 'shared/key' %>
      <%= render 'shared/happiness_overview', :type => type %>
      <%= render 'shared/metrics', :type => type %>
      <%= render 'shared/entries', :entries => entries %>
    <% else %>
      <div class='row-fluid'>
        <div class='center span12 no-entries'>
          <h3>Sorry! There are no happiness entries available for day you have chosen.</h3>
        </div>    
      </div>
    <% end %>

  </div>

</div>

app/views/dashboard/_month.html.erb
<div class="row-fluid">
  <div class='span12'>

      <div class='row-fluid title-block'>
        <div class='align-right span4'>
          <%= link_to "Previous month", other_month_path(current_beginning_of_month_day, :previous), :class => "btn" if current_beginning_of_month_day %>
        </div>
        <div class='center span4'>
           <h1>
              <%= current_beginning_of_month_day.strftime("%B") %>
              <%= link_to current_beginning_of_month_day.year, year_path(current_beginning_of_month_day.year), :class => "" %>
            </h1>
        </div>
        <div class='align-left span4'>
          <%= link_to "Following month", other_month_path(current_beginning_of_month_day, :next), :class => "btn" if current_beginning_of_month_day %>
        </div>      
      </div>

    <%= render 'shared/weeks' %>

    <% if entries.any? %>
      <%= render 'shared/key' %>
      <%= render 'shared/happiness_overview' %>
      <%= render 'shared/metrics', :type => type %>
      <%= render 'shared/graph', :entries => entries, :type => type %>
    <% else %>
      <div class='row-fluid'>
        <div class='center span12 no-entries'>
          <h3>Sorry! There are no happiness entries available for month you have chosen.</h3>
        </div>    
      </div>
    <% end %>



  </div>

</div>

app/views/dashboard/_week.html.erb
<div class="row-fluid">
  <div class='span12'>

      <div class='row-fluid title-block'>
        <div class='align-right span4'>
          <%= link_to "Previous week", other_week_path(current_beginning_of_week_day, :previous), :class => "btn" if current_beginning_of_week_day %>
        </div>
        <div class='center span4'>
           <h1><%= week_description(current_beginning_of_week_day, true) %></h1>
        </div>
        <div class='align-left span4'>
          <%= link_to "Following week", other_week_path(current_beginning_of_week_day, :next), :class => "btn" if current_beginning_of_week_day %>
        </div>      
      </div>

    <% if entries.any? %>
      <%= render 'shared/key' %>
      <%= render 'shared/happiness_overview' %>
      <%= render 'shared/metrics', :type => type %>
      <%= render 'shared/graph', :entries => entries, :type => type %>
    <% else %>
      <div class='row-fluid'>
        <div class='center span12 no-entries'>
          <h3>Sorry! There are no happiness entries available for week you have chosen.</h3>
        </div>    
      </div>
    <% end %>

  </div>

</div>

app/views/dashboard/_year.html.erb
<div class="row-fluid">
  <div class='span12'>

      <div class='row-fluid title-block'>
        <div class='align-right span4'>
          <%= link_to "Previous year", other_year_path(current_beginning_of_year_day, :previous), :class => "btn" if current_beginning_of_year_day %>
        </div>
        <div class='center span4'>
           <h2><%= current_beginning_of_year_day.strftime("%Y") %> </h2>
        </div>
        <div class='align-left span4'>
          <%= link_to "Following year", other_year_path(current_beginning_of_year_day, :next), :class => "btn" if current_beginning_of_year_day %>
        </div>      
      </div>

    <%= render 'shared/months' %>

    <% if entries.any? %>
      <%= render 'shared/key' %>
      <%= render 'shared/happiness_overview' %>
      <%= render 'shared/metrics', :type => type %>
      <%= render 'shared/graph', :entries => entries, :type => type %>
    <% else %>
      <div class='row-fluid'>
        <div class='center span12 no-entries'>
          <h3>Sorry! There are no happiness entries available for year you have chosen.</h3>
        </div>    
      </div>
    <% end %>

  </div>

</div>

app/views/dashboard/index.html.erb
<div class='row-fluid'>
  <div class='span5 offset2'>
    <h1>Welcome</h1>
    <blockquote>
      <p>Happimetrics is a tool to help visualise happiness over time, with the added context of custom business metrics added by you. Several different metric formats are supported, including currency, percentage and days, hours and minutes.</p><br/>
      <p>The chief objective of this tool is to allow quick corrolations to be drawn between average happiness percentages and average metric values calculated from data provided by you for a given time period, i.e. day, week, month, or year. As you add data for a time period, you will be able to how the new value compares to the average value for a given metric.</p><br/>
      <p>The most recent happiness data in this tool is extracted from the happiness data feed of NixonMcInnes. However, in order to demonstrate the longer ranges of time used in this tool, the majority of data has been generated. The generation of this happiness data aims to create mock happiness entries with a similar propensity to certain values as the real NixonMcInnes data.</p><br/>
      <p>A selection of example metrics have been added to help demonstrate the application, but you are free to <%= link_to "add your own", metrics_path %>. Some example data has also been added to show metrics in action. When you are viewing a particular period of time, you can add or update a particular metric value by simply typing the desired value in the provided text box</p>
    </blockquote>
  </div>
  <div class='span4'>
    <h2>Get started</h2>
    <blockquote>
      <% last_month = 1.month.ago.to_date %>
      <p>View last month: <%= link_to last_month.strftime("%B %Y"), month_path(last_month.month, last_month.year), :class => "btn" %></p><br/>
      <p>View the current year: <%= link_to Date.today.strftime("%Y"), year_path(Date.today.year), :class => "btn" %></p><br/>
      <p>Add some metrics: <%= link_to "Metrics", metrics_path, :class => "btn" %></p><br/>
    </blockquote>
    <h2>Hints</h2>
    <blockquote>
      <p>Click a data point on the graph to drill down to the given day or month</p></br>
      <p>Use the blue links in the title of the particular time period you are viewing to navigate to the given month or year.</p><br/>
      <p>Click the logo if you want to come back here at any point.</p>
    <blockquote>
  </div>
</div>

app/views/dashboard/show.html.erb
<%= render type.to_s %>